/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as OtsRouteImport } from './routes/ots'
import { Route as MntCommandRouteImport } from './routes/mnt-command'
import { Route as LabRouteImport } from './routes/lab'
import { Route as HseCenterRouteImport } from './routes/hse-center'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as DigitalLibraryRouteImport } from './routes/digital-library'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BiRouteImport } from './routes/bi'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulesPlantCodeRouteImport } from './routes/modules.$plantCode'
import { Route as DeptDeptIdRouteImport } from './routes/dept.$deptId'
import { Route as ModulePlantCodeModuleKeyRouteImport } from './routes/module.$plantCode.$moduleKey'

const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const OtsRoute = OtsRouteImport.update({
  id: '/ots',
  path: '/ots',
  getParentRoute: () => rootRouteImport,
} as any)
const MntCommandRoute = MntCommandRouteImport.update({
  id: '/mnt-command',
  path: '/mnt-command',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HseCenterRoute = HseCenterRouteImport.update({
  id: '/hse-center',
  path: '/hse-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalLibraryRoute = DigitalLibraryRouteImport.update({
  id: '/digital-library',
  path: '/digital-library',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesPlantCodeRoute = ModulesPlantCodeRouteImport.update({
  id: '/modules/$plantCode',
  path: '/modules/$plantCode',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptDeptIdRoute = DeptDeptIdRouteImport.update({
  id: '/dept/$deptId',
  path: '/dept/$deptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulePlantCodeModuleKeyRoute =
  ModulePlantCodeModuleKeyRouteImport.update({
    id: '/module/$plantCode/$moduleKey',
    path: '/module/$plantCode/$moduleKey',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/digital-library': typeof DigitalLibraryRoute
  '/hierarchy': typeof HierarchyRoute
  '/hse-center': typeof HseCenterRoute
  '/lab': typeof LabRoute
  '/mnt-command': typeof MntCommandRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRoute
  '/modules/$plantCode': typeof ModulesPlantCodeRoute
  '/module/$plantCode/$moduleKey': typeof ModulePlantCodeModuleKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/digital-library': typeof DigitalLibraryRoute
  '/hierarchy': typeof HierarchyRoute
  '/hse-center': typeof HseCenterRoute
  '/lab': typeof LabRoute
  '/mnt-command': typeof MntCommandRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRoute
  '/modules/$plantCode': typeof ModulesPlantCodeRoute
  '/module/$plantCode/$moduleKey': typeof ModulePlantCodeModuleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/developer': typeof DeveloperRoute
  '/digital-library': typeof DigitalLibraryRoute
  '/hierarchy': typeof HierarchyRoute
  '/hse-center': typeof HseCenterRoute
  '/lab': typeof LabRoute
  '/mnt-command': typeof MntCommandRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRoute
  '/modules/$plantCode': typeof ModulesPlantCodeRoute
  '/module/$plantCode/$moduleKey': typeof ModulePlantCodeModuleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/developer'
    | '/digital-library'
    | '/hierarchy'
    | '/hse-center'
    | '/lab'
    | '/mnt-command'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/modules/$plantCode'
    | '/module/$plantCode/$moduleKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/developer'
    | '/digital-library'
    | '/hierarchy'
    | '/hse-center'
    | '/lab'
    | '/mnt-command'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/modules/$plantCode'
    | '/module/$plantCode/$moduleKey'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/developer'
    | '/digital-library'
    | '/hierarchy'
    | '/hse-center'
    | '/lab'
    | '/mnt-command'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/modules/$plantCode'
    | '/module/$plantCode/$moduleKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  BiRoute: typeof BiRoute
  DashboardRoute: typeof DashboardRoute
  DeveloperRoute: typeof DeveloperRoute
  DigitalLibraryRoute: typeof DigitalLibraryRoute
  HierarchyRoute: typeof HierarchyRoute
  HseCenterRoute: typeof HseCenterRoute
  LabRoute: typeof LabRoute
  MntCommandRoute: typeof MntCommandRoute
  OtsRoute: typeof OtsRoute
  PlantRoute: typeof PlantRoute
  DeptDeptIdRoute: typeof DeptDeptIdRoute
  ModulesPlantCodeRoute: typeof ModulesPlantCodeRoute
  ModulePlantCodeModuleKeyRoute: typeof ModulePlantCodeModuleKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ots': {
      id: '/ots'
      path: '/ots'
      fullPath: '/ots'
      preLoaderRoute: typeof OtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mnt-command': {
      id: '/mnt-command'
      path: '/mnt-command'
      fullPath: '/mnt-command'
      preLoaderRoute: typeof MntCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hse-center': {
      id: '/hse-center'
      path: '/hse-center'
      fullPath: '/hse-center'
      preLoaderRoute: typeof HseCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-library': {
      id: '/digital-library'
      path: '/digital-library'
      fullPath: '/digital-library'
      preLoaderRoute: typeof DigitalLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$plantCode': {
      id: '/modules/$plantCode'
      path: '/modules/$plantCode'
      fullPath: '/modules/$plantCode'
      preLoaderRoute: typeof ModulesPlantCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept/$deptId': {
      id: '/dept/$deptId'
      path: '/dept/$deptId'
      fullPath: '/dept/$deptId'
      preLoaderRoute: typeof DeptDeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$plantCode/$moduleKey': {
      id: '/module/$plantCode/$moduleKey'
      path: '/module/$plantCode/$moduleKey'
      fullPath: '/module/$plantCode/$moduleKey'
      preLoaderRoute: typeof ModulePlantCodeModuleKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  BiRoute: BiRoute,
  DashboardRoute: DashboardRoute,
  DeveloperRoute: DeveloperRoute,
  DigitalLibraryRoute: DigitalLibraryRoute,
  HierarchyRoute: HierarchyRoute,
  HseCenterRoute: HseCenterRoute,
  LabRoute: LabRoute,
  MntCommandRoute: MntCommandRoute,
  OtsRoute: OtsRoute,
  PlantRoute: PlantRoute,
  DeptDeptIdRoute: DeptDeptIdRoute,
  ModulesPlantCodeRoute: ModulesPlantCodeRoute,
  ModulePlantCodeModuleKeyRoute: ModulePlantCodeModuleKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
