/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as OtsRouteImport } from './routes/ots'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabRouteImport } from './routes/lab'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BiRouteImport } from './routes/bi'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipmentEquipmentIdRouteImport } from './routes/equipment.$equipmentId'
import { Route as DeptDeptIdRouteImport } from './routes/dept.$deptId'
import { Route as DeptDeptIdPlantPlantIdRouteImport } from './routes/dept.$deptId.plant.$plantId'
import { Route as DeptDeptIdPlantPlantIdSectionSectionIdRouteImport } from './routes/dept.$deptId.plant.$plantId.section.$sectionId'

const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const OtsRoute = OtsRouteImport.update({
  id: '/ots',
  path: '/ots',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentEquipmentIdRoute = EquipmentEquipmentIdRouteImport.update({
  id: '/equipment/$equipmentId',
  path: '/equipment/$equipmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptDeptIdRoute = DeptDeptIdRouteImport.update({
  id: '/dept/$deptId',
  path: '/dept/$deptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeptDeptIdPlantPlantIdRoute = DeptDeptIdPlantPlantIdRouteImport.update({
  id: '/plant/$plantId',
  path: '/plant/$plantId',
  getParentRoute: () => DeptDeptIdRoute,
} as any)
const DeptDeptIdPlantPlantIdSectionSectionIdRoute =
  DeptDeptIdPlantPlantIdSectionSectionIdRouteImport.update({
    id: '/section/$sectionId',
    path: '/section/$sectionId',
    getParentRoute: () => DeptDeptIdPlantPlantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/hierarchy': typeof HierarchyRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/dept/$deptId/plant/$plantId': typeof DeptDeptIdPlantPlantIdRouteWithChildren
  '/dept/$deptId/plant/$plantId/section/$sectionId': typeof DeptDeptIdPlantPlantIdSectionSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/hierarchy': typeof HierarchyRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/dept/$deptId/plant/$plantId': typeof DeptDeptIdPlantPlantIdRouteWithChildren
  '/dept/$deptId/plant/$plantId/section/$sectionId': typeof DeptDeptIdPlantPlantIdSectionSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/bi': typeof BiRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/hierarchy': typeof HierarchyRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/ots': typeof OtsRoute
  '/plant': typeof PlantRoute
  '/dept/$deptId': typeof DeptDeptIdRouteWithChildren
  '/equipment/$equipmentId': typeof EquipmentEquipmentIdRoute
  '/dept/$deptId/plant/$plantId': typeof DeptDeptIdPlantPlantIdRouteWithChildren
  '/dept/$deptId/plant/$plantId/section/$sectionId': typeof DeptDeptIdPlantPlantIdSectionSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/documents'
    | '/hierarchy'
    | '/lab'
    | '/login'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/equipment/$equipmentId'
    | '/dept/$deptId/plant/$plantId'
    | '/dept/$deptId/plant/$plantId/section/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/documents'
    | '/hierarchy'
    | '/lab'
    | '/login'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/equipment/$equipmentId'
    | '/dept/$deptId/plant/$plantId'
    | '/dept/$deptId/plant/$plantId/section/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/bi'
    | '/dashboard'
    | '/documents'
    | '/hierarchy'
    | '/lab'
    | '/login'
    | '/ots'
    | '/plant'
    | '/dept/$deptId'
    | '/equipment/$equipmentId'
    | '/dept/$deptId/plant/$plantId'
    | '/dept/$deptId/plant/$plantId/section/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  BiRoute: typeof BiRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  HierarchyRoute: typeof HierarchyRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  OtsRoute: typeof OtsRoute
  PlantRoute: typeof PlantRoute
  DeptDeptIdRoute: typeof DeptDeptIdRouteWithChildren
  EquipmentEquipmentIdRoute: typeof EquipmentEquipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ots': {
      id: '/ots'
      path: '/ots'
      fullPath: '/ots'
      preLoaderRoute: typeof OtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment/$equipmentId': {
      id: '/equipment/$equipmentId'
      path: '/equipment/$equipmentId'
      fullPath: '/equipment/$equipmentId'
      preLoaderRoute: typeof EquipmentEquipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept/$deptId': {
      id: '/dept/$deptId'
      path: '/dept/$deptId'
      fullPath: '/dept/$deptId'
      preLoaderRoute: typeof DeptDeptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dept/$deptId/plant/$plantId': {
      id: '/dept/$deptId/plant/$plantId'
      path: '/plant/$plantId'
      fullPath: '/dept/$deptId/plant/$plantId'
      preLoaderRoute: typeof DeptDeptIdPlantPlantIdRouteImport
      parentRoute: typeof DeptDeptIdRoute
    }
    '/dept/$deptId/plant/$plantId/section/$sectionId': {
      id: '/dept/$deptId/plant/$plantId/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/dept/$deptId/plant/$plantId/section/$sectionId'
      preLoaderRoute: typeof DeptDeptIdPlantPlantIdSectionSectionIdRouteImport
      parentRoute: typeof DeptDeptIdPlantPlantIdRoute
    }
  }
}

interface DeptDeptIdPlantPlantIdRouteChildren {
  DeptDeptIdPlantPlantIdSectionSectionIdRoute: typeof DeptDeptIdPlantPlantIdSectionSectionIdRoute
}

const DeptDeptIdPlantPlantIdRouteChildren: DeptDeptIdPlantPlantIdRouteChildren =
  {
    DeptDeptIdPlantPlantIdSectionSectionIdRoute:
      DeptDeptIdPlantPlantIdSectionSectionIdRoute,
  }

const DeptDeptIdPlantPlantIdRouteWithChildren =
  DeptDeptIdPlantPlantIdRoute._addFileChildren(
    DeptDeptIdPlantPlantIdRouteChildren,
  )

interface DeptDeptIdRouteChildren {
  DeptDeptIdPlantPlantIdRoute: typeof DeptDeptIdPlantPlantIdRouteWithChildren
}

const DeptDeptIdRouteChildren: DeptDeptIdRouteChildren = {
  DeptDeptIdPlantPlantIdRoute: DeptDeptIdPlantPlantIdRouteWithChildren,
}

const DeptDeptIdRouteWithChildren = DeptDeptIdRoute._addFileChildren(
  DeptDeptIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  BiRoute: BiRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  HierarchyRoute: HierarchyRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  OtsRoute: OtsRoute,
  PlantRoute: PlantRoute,
  DeptDeptIdRoute: DeptDeptIdRouteWithChildren,
  EquipmentEquipmentIdRoute: EquipmentEquipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
